//
//  LocationInfo.swift
//  EJ Current
//
//  Created by Sasha on 3/16/21.
//

import Foundation


let ejDef: String = " \"Environmental justice is the fair treatment and meaningful involvement of all people regardless of race, color, national origin, or income, with respect to the development, implementation, and enforcement of environmental laws, regulations, and policies. \n \n This goal will be achieved when everyone enjoys: \n \n • The same degree of protection from environmental and health hazards, and \n • Equal access to the decision-making process to have a healthy environment in which to live, learn, and work.\" \n \n - U.S. EPA"

let hawkins1 = "Shaw, a small town in Southern Mississippi, was racially segregated based on previous redlining policies. The population of Shaw was identified as 40% “white” and 60% “black”. As a result of redlining, only 3% of the black population lived in integrated areas. The areas where the other 97% resided, were being neglected by receiving municipal services at a slower rate (or no rate at all) than white areas during this same period. These services included paved streets, sanitary sewers, and upgraded street lighting."
let hawkins2 = "As this was a violation of the constitutional rights of  black Americans, Andrew Hawkins and other black residents of Shaw filed a class-action lawsuit against the city. Initially, Hawkins' claim was dismissed because it was found that Shaw was not discriminating based on race, but was acting in the good of public interest by making investments in (mostly) white residential areas."
let hawkins3 = "In January 1971, the case was taken to Appeals Court, where the judge found the differences in Shaw’s residential areas could only be explained as being racial discrimination. The town had denied their black residents equal protection of the law. The decision to make investments in the white occupied areas of Shaw, but not the black occupied areas, was intentional."
let hawkins4 = "The town of Shaw was ordered to plan and submit a “program of improvements that will, within a reasonable time, remove the disparities that bear so heavily on black citizens of Shaw.” The town was also ordered to arrange a Bi-Racial Committee that worked on resolving discriminatory issues with the town’s (all-white) city council."
let hawkins5 = "Although the case was won in favor of the Hawkins', they continued to experience racism in Shaw. Following the landmark decision, Mary Lou Hawkins (spouse of Andrew Hawkins) was murdered by a police officer in Shaw. The Hawkins residency was also set on fire twice, with the second fire leading to the murder of Andrew and Mary Lous’ son, and two grandchildren."

let northRiver1 = "The North River Sewage Treatment Plant was constructed on eight blocks along the Hudson River, in West Harlem, New York. This plant was originally meant for a predominantly white neighborhood, but the plans were met with blowback from the community. The City Planning Commission decided upon a low-income neighborhood that they initially stated was unsuitable."
let northRiver2 = "After the treatment plant was constructed, residents in the area complained about unpleasant odors that were so potent that the residents were forced to close off all sources of fresh air in their homes. In addition to the unbearable smell the plant gave off, locals were also suffering from itchy eyes and disruptions to the respiratory system. To mitigate the harm done to the local West Harlem community, the city promised to build a state-park on top of the sewage plant. The 28-acre state park was finally completed in 1993, 24 years after it was first discussed."
let northRiver3 = "In 1991, the city began to acknowledge the residents' complaints and discovered the reason behind why the odor was as bad as it was, errors with the roof. Errors were made as a result of the EPA rushing the City to complete the project as a measure of protection for the Hudson River. The EPA’s (only) priority was the quality of the water, failing to take into account the air and environmental impacts this facility would have on the surrounding community."
let northRiver4 = "In 1992, a local environmental justice group (WHE ACT) sued the City and the City’s Department of Environmental Protection (DEP). After a settlement was agreed upon in 1993, the State and City of New York agreed to strictly enforce corrective actions, and paid WHE ACT and the Natural Resources Defense Council $1.1 million dollars for community investment."

let titleLosAl: String = "Los Alamos National Labratory (Manhattan Project) - 1942"
let losAl1 = "Los Alamos, a small town in New Mexico, is home to Los Alamos National Laboratory, which was a top-secret lab built for the creation of nuclear weapons during WWII. The San Ildefonso Pueblo allowed the U.S. government to use that land with the understanding that it would be given back to them after the war."
let losAl2 = "Throughout the next 50 years, people living in areas surrounding the LANL were not made aware of toxic waste that was seeping into their water, air, and land, as it was improperly disposed of. The original inhabitants of the area were not protected from environmental and health hazards.Negligent handling of toxic waste has led to the polluting of land surrounding Los Alamos."
let losAl3 = "High rates of thyroid and various cancers in that area are linked to the mishandling of toxic materials from the LANL. Because of dump sites like “Area G”, local communities are still being impacted. Environmental resources sacred to the culture of the locals are polluted with dangerous amounts of radiation."


let delano1 = "The Delano Grape Strike began in 1965, in San Joaquin Valley, California. It began because of the brutal conditions and unjust compensation farm workers were given. Included in the brutal conditions was the failure to disclose to the workers the effects of long-term pesticide exposure. The predominantly Mexican and Filipino workers were constantly exposed to pesticides causing sickness, injury, and even death. There was concern surrounding the pesticides, but the concern was mainly for the environment and not the workers who were constantly breathing in contaminated air."
let delano2 = "As the hazards of pesticides were becoming more publicized from people telling their stories, workers knew they needed more workplace protection. The NFWA and AWOC (later named UFW) joined forces and began spreading awareness of the dangers of pesticides for workers and consumers. In addition to the overall health hazards of these chemicals, they were conveying how this was part of a greater social justice issue."
let delano3 = "Cesar Chavez, founder of the NFWA, believed in nonviolent practices. This nonviolent precedent led to a boycott of table grapes from unethical growers, which received national coverage along with other movements. Contracts between the UFW and various table grape growers were signed by 1968. These contracts included improved working conditions and increased wages for the farm workers. The strikes and boycotts eventually ended in 1970 when a larger group of growers joined in and signed with the UFW."


let warren1 = "Warren County, a predominantly black county in North Carolina, was chosen for the location of a landfill that would contain toxic waste, specifically PCBs. Exposure to PCBs increases rates of various cancers, and immunological, neurological, and  liver issues. The waste for this landfill was soil contaminated from illegal dumping done to avoid environmental penalties. The state of North Carolina decided on Warren County for the dumping, ignoring the fact that it was not the most suitable environment because the toxins were likely to contaminate the county’s water supply."
let warren2 = "In an attempt to delay the dumping, the NAACP and residents near the landfill filed a lawsuit saying that the choosing of Warren County for the landfill over more suitable areas was racially charged, but the district court denied their request for preliminary injunctive relief. Before the site was established, 800 protesters attended a public hearing to try and stop the harm that would be done on an already vulnerable area. The sitting governor, Jim Hunt, ignored the resident’s cries and continued with the plan. Community members tried to fight this decision by traveling to Washington to meet with the EPA. but they learned that the EPA was in the process of doing the opposite of what they wanted. The EPA was loosening requirements on the required distance between a landfill and groundwater."
let warren3 = "Protestors were ready when the first trucks of contaminated soil made it to the dump. Patrol officers were assigned to the landfill, even though almost all of the protesting was done peacefully. Their peaceful tactics included laying on the road to block trucks from entering and marching. Over 500 protestors were arrested over a six week period."
let warren4 = "The construction of the dump continued despite the health and economic concerns of the surrounding community. The Warren County PCB Landfill protest was considered the “kick-off” of the environmental justice movement. Because of pressure from the public, Governor Hunt guaranteed that when technologically possible, the landfill would be detoxified. This detoxification process was completed in 2004."

